-- User providers

ALTER TABLE USERS ADD COLUMN MODE VARCHAR(16);
UPDATE USERS SET MODE = 'builtin';
ALTER TABLE USERS ALTER COLUMN MODE SET NOT NULL;

-- @mysql

ALTER TABLE USERS ADD COLUMN MODE VARCHAR(16);
UPDATE USERS SET MODE = 'builtin';
ALTER TABLE USERS MODIFY COLUMN MODE VARCHAR(16) NOT NULL;

-- @rollback

ALTER TABLE USERS DROP COLUMN IF EXISTS MODE;

-- @mysql-rollback

ALTER TABLE USERS DROP COLUMN MODE;
