-- Application ID
ALTER TABLE APPLICATION ALTER COLUMN ID VARCHAR(16);
ALTER TABLE APPGRANTS ALTER COLUMN APPLICATION VARCHAR(16);
ALTER TABLE ENVGRANTS ALTER COLUMN APPLICATION VARCHAR(16);
ALTER TABLE APPKEY ALTER COLUMN APPLICATION VARCHAR(16);
ALTER TABLE CONFIG ALTER COLUMN APPLICATION VARCHAR(16);
ALTER TABLE ENVIRONMENT ALTER COLUMN APPLICATION VARCHAR(16);
ALTER TABLE VERSION ALTER COLUMN APPLICATION VARCHAR(16);
ALTER TABLE VERSION_KEY ALTER COLUMN APPLICATION VARCHAR(16);

-- @mysql
ALTER TABLE APPLICATION MODIFY COLUMN ID VARCHAR(16);
ALTER TABLE APPGRANTS MODIFY COLUMN APPLICATION VARCHAR(16);
ALTER TABLE ENVGRANTS MODIFY COLUMN APPLICATION VARCHAR(16);
ALTER TABLE APPKEY MODIFY COLUMN APPLICATION VARCHAR(16);
ALTER TABLE CONFIG MODIFY COLUMN APPLICATION VARCHAR(16);
ALTER TABLE ENVIRONMENT MODIFY COLUMN APPLICATION VARCHAR(16);
ALTER TABLE VERSION MODIFY COLUMN APPLICATION VARCHAR(16);
ALTER TABLE VERSION_KEY MODIFY COLUMN APPLICATION VARCHAR(16);
