-- Ordering of environments

ALTER TABLE ENVIRONMENT ADD COLUMN ORDERNB INTEGER;
UPDATE ENVIRONMENT E SET ORDERNB = (SELECT COUNT(*) FROM ENVIRONMENT ES WHERE ES.APPLICATION = E.APPLICATION AND ES.NAME <= E.NAME);
ALTER TABLE ENVIRONMENT ALTER COLUMN ORDERNB SET NOT NULL;

-- @mysql

ALTER TABLE ENVIRONMENT ADD COLUMN ORDERNB INTEGER;

CREATE TEMPORARY TABLE ENVSOURCE (
	APPLICATION VARCHAR(16),
	NAME VARCHAR(80),
	ORDERNB INTEGER
);

INSERT INTO ENVSOURCE (APPLICATION, NAME, ORDERNB) SELECT ES.APPLICATION, ES.NAME, (
	SELECT COUNT( * ) 
	FROM ENVIRONMENT E
	WHERE E.APPLICATION = ES.APPLICATION
	AND E.NAME <= ES.NAME
	ORDER BY E.APPLICATION, E.NAME
) AS ESCOUNT
FROM ENVIRONMENT ES;

UPDATE ENVIRONMENT E, ENVSOURCE ES SET E.ORDERNB = ES.ORDERNB WHERE E.APPLICATION = ES.APPLICATION AND E.NAME = ES.NAME;

ALTER TABLE ENVIRONMENT MODIFY COLUMN ORDERNB INTEGER NOT NULL;

-- @rollback

ALTER TABLE ENVIRONMENT DROP COLUMN ORDERNB;
