-- Disabled users

-- Default
ALTER TABLE USERS ADD COLUMN DISABLED BOOLEAN;
UPDATE USERS SET DISABLED = FALSE;
ALTER TABLE USERS ALTER COLUMN DISABLED SET NOT NULL;

-- @rollback
ALTER TABLE USERS DROP COLUMN IF EXISTS DISABLED;

-- @mysql
ALTER TABLE USERS ADD COLUMN DISABLED BOOLEAN;
UPDATE USERS SET DISABLED = FALSE;
ALTER TABLE USERS MODIFY COLUMN DISABLED BOOLEAN NOT NULL;

-- @mysql-rollback
ALTER TABLE USERS DROP COLUMN DISABLED;
