-- Audit
CREATE TABLE EVENTS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	SECURITY VARCHAR(10) NOT NULL,
	USER VARCHAR(80) NOT NULL,
	CREATION TIMESTAMP NOT NULL,
	CATEGORY VARCHAR(80) NOT NULL,
	IDENTIFIER VARCHAR(80) NULL,
	OLDVALUE VARCHAR(200) NULL,
	NEWVALUE VARCHAR(200) NULL,
	MESSAGE VARCHAR(600) NULL,
	CONSTRAINT PK_EVENTS PRIMARY KEY (ID) 
);

-- @rollback

DROP TABLE IF EXISTS EVENTS;
