-- User display name
ALTER TABLE USERS ADD COLUMN DISPLAYNAME VARCHAR(80) NULL;
UPDATE USERS SET DISPLAYNAME = NAME;
ALTER TABLE USERS ALTER COLUMN DISPLAYNAME SET NOT NULL;

-- @rollback
ALTER TABLE USERS DROP COLUMN IF EXISTS DISPLAYNAME;

-- @mysql
ALTER TABLE USERS ADD COLUMN DISPLAYNAME VARCHAR(80) NULL;
UPDATE USERS SET DISPLAYNAME = NAME;
ALTER TABLE USERS MODIFY COLUMN DISPLAYNAME VARCHAR(80) NOT NULL;

-- @mysql-rollback
ALTER TABLE USERS DROP COLUMN DISPLAYNAME;
